version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/circuit-breaker
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Environment.CIRCLE_SHA1 }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - vendor
  test:
    docker:
      - image: circleci/php:7.2-node-browsers
        environment:
          CODECOV_TOKEN: 01e0fd5c-d23b-4efa-a2fc-544e54a74996
    working_directory: ~/circuit-breaker
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Environment.CIRCLE_SHA1 }}
            - composer-v1-
      - run: ./vendor/bin/phpunit
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
