version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2.4
        environment:
          CODECOV_TOKEN: 01e0fd5c-d23b-4efa-a2fc-544e54a74996
    working_directory: ~/circuit-breaker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c5:57:fd:7f:d1:d6:d5:03:99:da:4d:83:a4:8f:91:32"
      - checkout
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit
      - run: bash <(curl -s https://codecov.io/bash)
